name: Build LaTeX PDF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Optional cache to speed up LaTeX installs
      - name: Cache TeXLive packages
        uses: actions/cache@v4
        with:
          path: ~/.texlive
          key: texlive-${{ runner.os }}-v1
          restore-keys: |
            texlive-${{ runner.os }}-

      - name: Compile LaTeX (latexmk + bibtex)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_lualatex: false
          latexmk_use_xelatex: false
          latexmk_shell_escape: true
          # Runs: pdflatex → bibtex → pdflatex → pdflatex
          extra_system_packages: "ghostscript poppler-utils"

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: URF-Astro-V2-PDF
          path: |
            main.pdf
          if-no-files-found: error


  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: URF-Astro-V2-PDF
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/main.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

